/*
 * Fronteira.java
 *
 * Created on 14 de Dezembro de 2007, 19:57
 */

package br.cefetrn.datinf.pdv.visao;

import br.cefetrn.datinf.estoque.dominio.ItemProduto;
import br.cefetrn.datinf.estoque.dominio.ItemVenda;
import br.cefetrn.datinf.estoque.dominio.Venda;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.UIManager;
import br.cefetrn.datinf.pdv.ISistema;

/**
 *
 * @author  wilbert
 */
public class telaPrincipal extends javax.swing.JFrame{
    
    private ISistema sistema;
    private Venda venda = null;
    private ItemVenda itemVendaEspera = null;
    /** Creates new form Fronteira */
    public telaPrincipal(ISistema sistema) {
        this.sistema = sistema;
        initComponents();
        this.temporizador();
        this.setLookAndFell();
        jTextFieldQuantidade.requestFocusInWindow();
        
    }
    
    
    private void iniciarVenda(){
        this.venda = sistema.iniciarVenda();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNomeProduto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jTextFieldQuantidade = new javax.swing.JTextField();
        jTextFieldSubTotal = new javax.swing.JTextField();
        jLabelHora = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("eVendas");

        jTextFieldNomeProduto.setFont(new java.awt.Font("Tahoma", 0, 48));
        jTextFieldNomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarProduto(evt);
            }
        });

        jList1.setFont(new java.awt.Font("Tahoma", 0, 24));
        jScrollPane1.setViewportView(jList1);

        jTextFieldQuantidade.setFont(new java.awt.Font("Tahoma", 0, 48));
        jTextFieldQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldQuantidadeKeyPressed(evt);
            }
        });

        jTextFieldSubTotal.setFont(new java.awt.Font("Tahoma", 0, 48));

        jLabelHora.setText("0");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48));
        jLabel1.setText("Subtotal");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36));
        jLabel2.setText("Produtos");

        jLabel3.setText("F5 (Cupom de troca)");

        jButton1.setText("jButton1");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldQuantidade)
                            .addComponent(jTextFieldNomeProduto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelHora)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jButton1)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabelHora))
                        .addGap(41, 41, 41)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jTextFieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldQuantidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldQuantidadeKeyPressed
        int codigo = evt.getKeyCode();
        
        if(codigo == 10){
            JOptionPane.showMessageDialog(null, "Codigo" + codigo);
        }    
        
        if(codigo == 116){
            gerarCupom = new GerarCupom(this);
            gerarCupom.setVisibleDialog(true);
        }
        
    }//GEN-LAST:event_jTextFieldQuantidadeKeyPressed

    private void buscarProduto(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarProduto
      exibirItemVenda();
    }//GEN-LAST:event_buscarProduto

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked
    
    private void exibirItemVenda(){
         itemVendaEspera = sistema.criarItemVenda(Integer.parseInt(jTextFieldNomeProduto.getText()));
         jTextFieldNomeProduto.setFont(new java.awt.Font("Tahoma", 0,15));
         ItemProduto itemProduto = itemVendaEspera.getItemProduto();
         jTextFieldNomeProduto.setText("Produto: "+itemProduto.getProduto().getNome()+
                 " - Preço: R$ "+itemProduto.getPreco());
    }
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaPrincipal().setVisible(true);
            }
        });
    }*/

    private void setLookAndFell() {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception e) {
        
        } 
    }
    
    
    
    private void temporizador(){
        ActionListener action = new ActionListener() {
            String formato = "H:m:s";
            SimpleDateFormat simpleDateFormat = new SimpleDateFormat(formato);
            
            
            public void actionPerformed(ActionEvent e) {
                String hora = simpleDateFormat.format(Calendar.getInstance().getTime());
                telaPrincipal.this.jLabelHora.setText(hora);
            }
        };
        
        Timer timer = new Timer(1000, action);
        timer.start();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldNomeProduto;
    private javax.swing.JTextField jTextFieldQuantidade;
    private javax.swing.JTextField jTextFieldSubTotal;
    // End of variables declaration//GEN-END:variables
    private GerarCupom gerarCupom;

    
}
